# Generated by Django 5.2 on 2025-04-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='images/ava-img.jpeg', upload_to='profile_images/'),
        ),
    ]
