# Generated by Django 5.2 on 2025-04-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0003_category_image_category_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
    ]
