# Generated by Django 5.2 on 2025-04-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0005_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsuggestion',
            name='supports',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaintsuggestion',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
